### ISSUE TITLE
v4.7.x no longer works with webpack.UglifyJS

### ISSUE THREAD

**Issue by mkools-vg** [ReactTraining/history#514]
```
[ Error: main-12ebefd36dfec92d3cbc.js from UglifyJs
  SyntaxError: Unexpected token: keyword (var) [./~/history/PathUtils.js:1,0]
      at .\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:128:32
      at Array.forEach (native)
      at Compilation.<anonymous> (.\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:44:10)
      at Compilation.applyPluginsAsync (.\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
      at Compilation.<anonymous> (.\node_modules\webpack\lib\Compilation.js:567:9)
      at Compilation.applyPluginsAsync (.\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Compilation.<anonymous> (.\node_modules\webpack\lib\Compilation.js:563:8)
      at Compilation.applyPluginsAsync (.\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Compilation.seal (.\node_modules\webpack\lib\Compilation.js:525:7)
      at Compiler.<anonymous> (.\node_modules\webpack\lib\Compiler.js:397:15)
      at .\node_modules\webpack\node_modules\tapable\lib\Tapable.js:103:11
      at Compilation.<anonymous> (.\node_modules\webpack\lib\Compilation.js:445:10)
      at .\node_modules\webpack\lib\Compilation.js:417:12
      at .\node_modules\webpack\lib\Compilation.js:332:10
      at .\node_modules\async\lib\async.js:52:16
      at done (.\node_modules\async\lib\async.js:246:17)
      at .\node_modules\async\lib\async.js:44:16
      at .\node_modules\webpack\lib\Compilation.js:332:10
      at .\node_modules\async\lib\async.js:52:16
      at done (.\node_modules\async\lib\async.js:246:17)
      at .\node_modules\async\lib\async.js:44:16
      at .\node_modules\webpack\lib\Compilation.js:332:10
      at .\node_modules\async\lib\async.js:52:16
      at done (.\node_modules\async\lib\async.js:246:17)
      at .\node_modules\async\lib\async.js:44:16
      at .\node_modules\webpack\lib\Compilation.js:332:10
      at .\node_modules\async\lib\async.js:52:16
      at done (.\node_modules\async\lib\async.js:246:17)
      at .\node_modules\async\lib\async.js:44:16
      at .\node_modules\webpack\lib\Compilation.js:332:10 ]
```
This is with webpack 1.x

**Comment by wssgcg1213** [comment]
see #513 , fixed in 4.7.2

**Comment by mkools-vg** [comment]
Thanks, looks like it works now!

**Comment by mjackson** [comment]
Thanks @wssgcg1213 :)
